### PR TITLE
Clip beak and eye from the rest and add fill class

### PR DESCRIPTION
**Pull request by jelovirt**
## Description
In the existing logo the eye and beak are filled with white. When the logo is used with a non-white background, the eye and the beak do not use the background color as the rest of the logo.

The eye and beak were clipped from the rest of the logo, removing their own paths. Now the whole logo is a single path.

Added `logo` class to allow creating a negative logo.

## Motivation and Context
The logo must be usable with non-white background and a negative logo is required for dark backgrounds.

Original and updated logos on a background. The update logo's fill has been changed in the HTML style:

Screenshot_2019-03-23 test

### CODE REVIEW

**Review by infotexture — COMMENTED** [review]
We could view this as a solution for dark backgrounds as proposed in #4, but I wonder if it would be better to create a dedicated variant for that purpose as originally proposed there. 

Retaining a variant with the white eye & beak would ensure good contrast of those elements with the primary color in cases where the background color might not, but I'm not sure if it's worth maintaining separate variants for these edge cases.

@SanFanDocu Any preference?

**Comment by infotexture** [comment]
@jelovirt Would the specificity of the inline `<style>` element within the `<svg>` element permit overrides to the fill color in the surrounding HTML/(S)CSS without modifications to the .svg file?

I tried adding a corresponding rule to our stylesheets, but wasn't able to override the fill even with `!important`.

**Comment by jelovirt** [comment]
@infotexture You can't override styles for referenced SVG. Only embedded SVG images can use the HTML's style definitions.

**Review by infotexture — APPROVED** [review]
👍 This will make it easier to create a dark background variant for #4.

**Pull request merged**
